[build]
  command = "npm run build"
  publish = ".output/public"

[build.environment]
  NODE_VERSION = "20"

# Redirects all traffic to index.html for client-side routing fallback if static rendering
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
